{
 "title": "[Your Application] - HTTP",
 "description": "HTTP metrics for [Your Application] service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Mean response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m])/rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Response time of 50%, 75%, 90%, 95% of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Top APIs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by(uri, method) (rate(http_server_requests_seconds_count[1m])))"
    }
   ]
  }
 ]
}